### PR TITLE
I346 csv indentation

### LINKED ISSUE #346: Bulk Add User Sample CSV improvements
This probably applies to both non-umich and umich user sample CSVs.

The existing CSV for UM users has the sample data is reversed (under the wrong headers). I think it would be fine to have just one sample data row for a user with student role rather than all the roles. Users of this tool can reference the documentation should they want to know what other roles are available for use with this tool.

The same can be true for non-umich users sample download file.

### PR DESCRIPTION
**Pull request by pushyamig**
Fixes #346 

This PR is fixing the indentation problem that was not fixed PR #355

### CODE REVIEW

File: ccm_web/client/src/components/SingleSectionEnrollmentWorkflow.tsx [hunk 1]
```diff
@@ -213,8 +213,8 @@ export default function SingleSectionEnrollmentWorkflow (props: SingleSectionEnr
     if (rowInvalidations !== undefined) return renderRowValidationErrors(rowInvalidations)
 
     const fileData =
-    `${REQUIRED_ENROLLMENT_HEADERS.join(',')}
-    studentone, student`
+    `${REQUIRED_ENROLLMENT_HEADERS.join(',')}\n` +
+    'studentone, student\n'
```
Comment (ssciolla) [inline ccm_web/client/src/components/SingleSectionEnrollmentWorkflow.tsx:217]:
```suggestion
    'studentone,student\n'
```

**Review by ssciolla — APPROVED** [review]
