### PR TITLE
418 FE deps update fix UI bugs and unmerging issue

### LINKED ISSUE #408: Unmerging feature is not working
The Unmerging for  course section could be done from 2 places. The unmerging is not working when we open the `Merge Section` from landing page and if there are sections that are listed in the right column that are crosslisted into the current course.  

Console log show this error

```
Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>.
    at button
    at ButtonBase (https://8831-141-213-171-192.ngrok-free.app/main-578b7839b959ef2f659a.js:1711:22)
    at WithStyles (https://8831-141-213-171-192.ngrok-free.app/main-578b7839b959ef2f659a.js:23708:31)
    at Button (https://8831-141-213-171-192.ngrok-free.app/main-578b7839b959ef2f659a.js:1469:24)
    at WithStyles (https://8831-141-213-171-192.ngrok-free.app/main-578b7839b959ef2f659a.js:23708:31)
    at p
    at Typography (https://8831-141-213-171-192.ngrok-free.app/main-578b7839b959ef2f659a.js:18489:28)
    at WithStyles (https://8831-141-213-171-192.ngrok-free.app/main-578b7839b959ef2f659a.js:23708:31)
    at div
```

### PR DESCRIPTION
**Pull request by jaydonkrooss**
FE Dependency Updates: Minor package updates and addresses UI bugs found in https://github.com/tl-its-umich-edu/canvas-course-manager-next/issues/418
Fixes #408
Bugs addressed:

- Pagination is broken (styling of pagination buttons)
- Error alert styling is broken (Try again window)
- Error icon is red (Review your CSV file) color is changed to blue
- course Name component being misaligned, and edit box was too large
- Gradebook formatter requirement list styling was misaligned
- CustomTable selectprops being deprecated
- Merge Sections selector list, sections were not properly disabled
- Text alignment for BulkSectionCreate, GradebookCanvas, and MergeSections

Also uses material UI upgrade ListItem props to fix the https://github.com/tl-its-umich-edu/canvas-course-manager-next/issues/408

Bugs not identified:

- Alignment issue b/w small and big window inside features workflow
- Unmerging text/spinner is missing when unmerging feature
- Create single Section textbox has alignment issue

### CODE REVIEW

File: ccm_web/client/src/components/Alert.tsx [hunk 1]
```diff
@@ -15,16 +15,17 @@ const StyledGrid = styled(Grid)((
     theme
   }
```
Comment (pushyamig) [inline ccm_web/client/src/components/Alert.tsx:16]: I see some linting waring saying theme this never used? This happens in 2 places in this file. Might need to remove it?

File: ccm_web/client/src/components/CustomTable.tsx [hunk 2]
```diff
@@ -78,10 +78,6 @@ function CustomTable<T extends TableEntity> (props: TableProps<T>): JSX.Element
               count={tableRows.length}
               rowsPerPage={rowsPerPage}
               page={page}
-              SelectProps={{
-                inputProps: { 'aria-label': 'rows per page' },
-                native: true
-              }}
```
Comment (pushyamig) [inline ccm_web/client/src/components/CustomTable.tsx:84]: I see this was deprecated in MUI. was there a replacement needed? or is deleting this did not had any side effects?

File: ccm_web/client/src/components/Alert.tsx [hunk 3]
```diff
@@ -49,11 +49,11 @@ export default function Alert (props: AlertProps): JSX.Element {
   const { title, icon, embedded, children } = props
 
   const core = (
-    <Paper className={`${classes.dialog} ${classes.padding}`} role='alert'>
```
Comment (pushyamig) [inline ccm_web/client/src/components/Alert.tsx:52]: Why is `StyledCorePare` component used?

Comment (pushyamig) [reply ccm_web/client/src/components/Alert.tsx:52]: I see you have wrapped this with Paper. Can you tell me what was the need for this?

**Comment by pushyamig** [comment]
What exact styling fixed the pagination mis-alignment?

File: ccm_web/client/src/components/SectionSelectorWidget.tsx [hunk 4]
```diff
@@ -594,7 +599,7 @@ function SectionSelectorWidget (props: ISectionSelectorWidgetProps): JSX.Element
                 divider
                 disableGutters
                 classes={{ root: classes.listItemRoot }}
-                selected={isSelected}
```
Comment (pushyamig) [inline ccm_web/client/src/components/SectionSelectorWidget.tsx:597]: Did this changed fixed the message saying "Unmerging"?

Comment (pushyamig) [reply ccm_web/client/src/components/SectionSelectorWidget.tsx:597]: I think Unmerging issue #408 seems to solved. is this the change that fixed it?

**Comment by pushyamig** [comment]
Overall I see all the styling issues seems to be solved including the unmerging bug. I have one issue with linting and some questions on PR about the approach, if those are resolved this PR is ready to be merged. Nice work @jaydonkrooss !

**Comment by pushyamig** [comment]
@jaydonkrooss Let's have this merged today or Tomorrow. Then I can take this change to my PR with CSRF library move.

File: ccm_web/client/src/components/SectionSelectorWidget.tsx (hunk 4 above)
Comment (jaydonkrooss) [reply ccm_web/client/src/components/SectionSelectorWidget.tsx:597]: Yes, this was to to address the unmerging bug. I think secondaryAction was introduced for ListItems for the purpose of having another button component in an item, I saw some examples that I took as inspiration from the react docs https://mui.com/material-ui/react-list/  as for the "Unmerging" message, I never identified that as a UI bug, but its possible the styling tweaks I added brought it back to a normal state.

File: ccm_web/client/src/components/Alert.tsx (hunk 3 above)
Comment (jaydonkrooss) [reply ccm_web/client/src/components/Alert.tsx:52]: This component sometimes returns core (just the paper component) by itself (in the case of an embedded alert), and in those situations the styling wasn't working so I manually styled the Paper component with emotion. From what I saw it properly styled the returned alert in these cases. Just a bug with the codemod that didn't handle this case

File: ccm_web/client/src/components/Alert.tsx (hunk 1 above)
Comment (jaydonkrooss) [reply ccm_web/client/src/components/Alert.tsx]: I just committed a rewrite of the styles to make it a little more simplified, I realized I needed theme for a padding style that I forgot to add.

File: ccm_web/client/src/components/CustomTable.tsx (hunk 2 above)
Comment (jaydonkrooss) [reply ccm_web/client/src/components/CustomTable.tsx:84]: I don't think this snippet was actually having any effect, since these props are supposed to be used within the tablePagination footer. I think its possible that it must have been from a previous version or copied from a template that had an option to change the number of rows per page (hence the use of inputProps). After removing this, the aria-labels look the same when I compare to production.

**Comment by jaydonkrooss** [comment]
> What exact styling fixed the pagination mis-alignment?
Screenshot 2024-03-26 at 4 07 29 PM

When you said that pagination was broken, I thought that might have referred to the pagination buttons not being in the correct flex configuration. maybe misalignment is the wrong word, but it required a small styling change to make sure they were all listed in one row as seen in the picture (it used to be split into two rows)

**Review by pushyamig — APPROVED** [review]
